---

- name: config | resolved
  become: true
  tags:
    - systemd.resolved
  block:

    - name: config | create resolved.conf.d
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: config | create resolved.conf
      ansible.builtin.template:
        src: resolved.conf.j2
        dest: /etc/systemd/resolved.conf.d/resolved.conf
        owner: root
        group: root
        mode: '0644'
        lstrip_blocks: true
      notify:
        - resolved | restart
        - resolvconf | disable

- name: config | timesyncd
  become: true
  tags:
    - systemd.timesyncd
  block:

    - name: config | create timesyncd.conf
      ansible.builtin.template:
        src: timesyncd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        owner: root
        group: root
        mode: '0644'
        lstrip_blocks: true
      when:
        - systemd_timesyncd | length > 0
      notify:
        - timesyncd | restart

- name: config | networkd
  become: true
  tags:
    - systemd.networkd
  when:
    - systemd_all_networkd | default('') | length > 0
  block:

    - name: config | create networkd
      block:

        - name: config | create networkd links
          ansible.builtin.template:
            src: networkd.link.j2
            dest: /etc/systemd/network/{{ item.priority }}-{{ item.name }}.link
            owner: root
            group: root
            mode: '0644'
            lstrip_blocks: true
          register: systemd_networkd_netlinks
          loop: '{{ systemd_all_networkd | sort(attribute="name") }}'
          loop_control:
            label: '{{ item.name }}'
          when:
            - item.kind == 'link'
          notify:
            - networkd | restart

        - name: config | create networkd devices
          ansible.builtin.template:
            src: networkd.netdev.j2
            dest: /etc/systemd/network/{{ item.priority }}-{{ item.name }}.netdev
            owner: root
            group: root
            mode: '0644'
            lstrip_blocks: true
          register: systemd_networkd_netdevs
          loop: '{{ systemd_all_networkd | sort(attribute="name") }}'
          loop_control:
            label: '{{ item.name }}'
          when:
            - item.kind not in ['ether', 'link', 'loopback']
          notify:
            - networkd | restart

        - name: config | create networkd interfaces
          ansible.builtin.template:
            src: networkd.network.j2
            dest: /etc/systemd/network/{{ item.priority }}-{{ item.name }}.network
            owner: root
            group: root
            mode: '0644'
            lstrip_blocks: true
          register: systemd_networkd_networks
          loop: '{{ systemd_all_networkd | sort(attribute="name") }}'
          loop_control:
            label: '{{ item.name }}'
          when:
            - item.kind != 'link'
          notify:
            - networkd | restart

        - name: config | create networkd slaves
          ansible.builtin.template:
            src: networkd.slaves.j2
            dest: /etc/systemd/network/{{ item.priority }}-{{ item.name }}-slaves.network
            owner: root
            group: root
            mode: '0644'
            lstrip_blocks: true
          register: systemd_networkd_slaves
          loop: '{{ systemd_all_networkd | sort(attribute="name") }}'
          loop_control:
            label: '{{ item.name }}'
          when:
            - item.kind in ['bridge', 'bond']
            - item.slaves | default([]) | length > 0
          notify:
            - networkd | restart

    - name: config | clean networkd
      block:

        - name: config | get all networkd configurations
          ansible.builtin.find:
            depth: 1
            file_type: file
            paths: /etc/systemd/network
            patterns:
              - '*.link'
              - '*.netdev'
              - '*.network'
          register: systemd_networkd_all_devices

        - name: config | set used networkd configurations
          ansible.builtin.set_fact:
            systemd_networkd_managed_devices: '{{ systemd_networkd_managed_devices | default([]) + item }}'
          loop:
            - '{{ systemd_networkd_netlinks | json_query("results[*].dest") }}'
            - '{{ systemd_networkd_netdevs | json_query("results[*].dest") }}'
            - '{{ systemd_networkd_networks | json_query("results[*].dest") }}'
            - '{{ systemd_networkd_slaves | json_query("results[*].dest") }}'
          loop_control:
            label: '{{ item }}'
          when:
            - item | length > 0

        - name: config | clean unused networkd configurations
          ansible.builtin.file:
            path: '{{ item.path }}'
            state: absent
          loop: '{{ systemd_networkd_all_devices.files }}'
          loop_control:
            label: '{{ item.path | basename }}'
          when:
            - systemd_networkd_all_devices.files | length > 0
            - item.path not in systemd_networkd_managed_devices | default([])

        - name: config | disable networking interfaces
          ansible.builtin.copy:
            dest: /etc/network/interfaces
            mode: preserve
            content: |
              #
              # Ansible managed
              #

              # DO NOT EDIT HERE
              # We DO NOT USE legacy networking scripts. Use systemd-networkd instead
              # See /etc/systemd/network for configuration files
          notify:
            - networking | disable
            - system | reboot

- name: config | firewall
  become: true
  tags:
    - systemd.firewalld
  block:

    - name: config | create firewalld.conf
      ansible.builtin.template:
        src: firewalld.conf.j2
        dest: /etc/firewalld/firewalld.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - firewalld | restart

    - name: config | apply firewalld rules
      ansible.posix.firewalld:
        interface: '{{ item.interface | default(omit) }}'
        masquerade: '{{ item.masquerade | default(omit) }}'
        permanent: '{{ item.permanent | default(omit) }}'
        port: '{{ item.port | default(omit) }}'
        port_forward: '{{ item.port_forward | default(omit) }}'
        protocol: '{{ item.protocol | default(omit) }}'
        rich_rule: '{{ item.rich_rule | default(omit) }}'
        service: '{{ item.service | default(omit) }}'
        source: '{{ item.source | default(omit) }}'
        state: '{{ item.state | default(omit) }}'
        target: '{{ item.target | default(omit) }}'
        zone: '{{ item.zone | default(omit) }}'
      loop: '{{ systemd_all_firewalld }}'
      loop_control:
        label: '{{ item.name }}'
      notify:
        - firewalld | validate
