---

fail2ban:
  children:
    vps:

home:
  children:
    pi:

pi:
  hosts:
    opi5-8:
    opi5-16:
    rpi4:

timeweb:
  hosts:
    timeweb-ru:

vdsina:
  hosts:
    vdsina-nl:
    vdsina-ru:

vps:
  children:
    timeweb:
    vdsina:
